### ISSUE TITLE
Incorrect pitch on mobile devices

### ISSUE THREAD

**Issue by earboxer** [rism-digital/midi-player#21]
You can test this by pressing play on https://www.verovio.org/mei-viewer.xhtml

It seems detuned (usually roughly one semitone out of tune)

|Device|Browser|Pitch/Tempo|
|----|-----|-----|
|OnePlus 3T on Android 7.1.1| Firefox 68.9.0esr | Slightly Higher/Faster|
|iPhone 6s|Safari on iOS 13.4.1|Slightly Higher/Faster|
|Macbook Pro mid-2014|Firefox 76.0.1|Normal|
|Macbook Pro mid-2014|Chrome 79 | Normal|
|iPad 6th Gen|Safari on iOS 13.5|Slightly lower/slower|
| unspecified android device | samsung browser | slightly higher/faster|

**Comment by lpugin** [comment]
Thanks for the detailed report. I am aware of this issue but have absolutely no idea how to solve it. I once tried to look at it but could not find anything. I suspect it is in the WildMIDI port to WebAssembly.

**Comment by efreja** [comment]
Tested earboxer's fix in midi-player, and it solves the problem. Thanks!

**Comment by craigsapp** [comment]
I suspect that it is a sampling rate issue, where different implementations/hardware have different audio sampling rates.  Probably the slower ones use 44.1 kHz and the faster ones use 48 kHz.   But then I do not know why there would be 3 different speeds: maybe 32 KHz for the slower and/or there is a bug in the timing clock timing for webaudio on certain platforms.

The difference between 44.1 kHz and 48 kHz is 147 cents (which is 1.47 semitones).  `cents = log_2(48/44.1)*1200`.  If the mid-to-lower interval is also 1.47, then it could be a mixup in the 44.1/48 kHz sampling rates in the other direction.

Probably there is a fixed sampling rate set in WildWebMidi, but there should be some function in WebAudio that gives the hardware sampling rate, and this value needs to be given to WildWebMidi's audio interface.
