### ISSUE TITLE
Last note played again when song played twice

### ISSUE THREAD

**Issue by efreja** [rism-digital/midi-player#23]
Hello,

Apparently, the code of this lib does not perform correct cleanup when playback ends or is stopped.
Indeed, it always plays the last note heard first, from a previous playback.

I have noticed that this behaviour does not happen with Firefox, but can be heard with Chrome or Safari.

As the Verovio viewer uses the midi-player, you can hear it with:

https://www.verovio.org/mei-viewer.xhtml

On example Schubert_Lindenbaum.mei

With Chrome or Safari, play it to the end, then replay it : you'll hear again repeated the last note of the song, before the first note of the piece.
And it's not necessarily the last note of the example; if I stop before the end on another note, that another note is the one we will hear at the beginning of any new playback.

It seems a detail but for some advanced usages of the lib, it is quite annoying.

Thanks

**Comment by craigsapp** [comment]
Yes, this is some sort of audio buffering problem.  When the MIDI file is finished playing, there is still audio left in the buffer (probably reverb) left after the music stops which is not played.  When MIDI file finished playing, the audio buffer is not completely empty, so the leftover audio in the buffer gets played.   I looked at the code a few years ago and could not find where or how to clear the buffer.  If there is a buffer-clearing function of some sort, then running that before starting to play a new MIDI file should work.

**Comment by efreja** [comment]
For me it may come from :

https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode

tha says that :

An AudioBufferSourceNode can only be played once

I've made some tests than can give you some trails.
Create function:

```
function resetAudio() {
    scriptNode = audioCtx.createScriptProcessor(BUFFER, 0, channels);
    scriptNode.onaudioprocess = onAudioProcess;
    
    source = audioCtx.createBufferSource();
    circularBuffer = new CircularAudioBuffer(8);
    emptyBuffer = audioCtx.createBuffer(channels, BUFFER, SAMPLE_RATE);
    
    source.connect(scriptNode);
    source.start(0);
    console.debug("resetAudio");
}

```
and call it inside stop()

```
function stop() {
    _EM_signalStop = 1;
    _EM_seekSamples = 0;
    resetAudio();
    
    midiPlayer_totalSamples = 0;
    midiPlayer_currentSamples = ULONG_MAX;
    midiPlayer_progress.style.width = '0%';
    midiPlayer_playingTime.innerHTML = "00.00";
    midiPlayer_totalTime.innerHTML = "00.00";
    
    midiPlayer_play.style.display = 'none';
    midiPlayer_pause.style.display = 'none';
    midiPlayer_stop.style.display = 'none';
    
    if (midiPlayer_onStop != null) midiPlayer_onStop(); 
}

```
The problem is that it works on Chrome but not any longer on Firefox... nor Safari..

Hope it can help giving some ideas...

**Comment by craigsapp** [comment]
This function looks promising:

```javascript
  resetAudio();
```

By the name of it, I seems like it might set the samples in the audio buffers to all 0, which is what needs to be done to get rid of the annoying extra note residual.

And the important part of that function in the first code block:

```javascript
    source = audioCtx.createBufferSource();
    circularBuffer = new CircularAudioBuffer(8);
    emptyBuffer = audioCtx.createBuffer(channels, BUFFER, SAMPLE_RATE);
```

Looks like it is creating a new audio buffer, which would automatically start with samples set to 0.0 in the buffer.

The circularBuffer could be where the reverb sounds is getting stuck:

```javascript
    circularBuffer = new CircularAudioBuffer(8);
```

Being able to clear such a variable in WildWestMIDI and/or continuing the play the MIDI file for a second after it ends should be a way to get rid of the sound stuck in the buffer.   The best option would be to play the audio for a second or so after the MIDI file to allow for a graceful end in the MIDI file playback (rather than having it cut off abruptly).

**Comment by efreja** [comment]
For me that function that calls stop after 1sec as you say for 'gracefully ending the MIDI file playback ', does the job:

```
function completeConversion(status) {
    midiPlayer_drainBuffer = true;
    console.debug('completeConversion');
    midiPlayer_convertionJob = null;
    // Not a pause
    if (_EM_signalStop != 2) {
        setTimeout(stop, 1000);   
    }
}
```
so stop() is called either at the end of the playback or when stop button is pressed.

So it seems quite close to the solution, but ... this code makes things worse on Firefox... don't know why...

**Comment by efreja** [comment]
Any idea if/when this issue could be corrected ? Thanks

**Comment by craigsapp** [comment]
As soon as someone submits a PR :-).  I could look at it this summer (I should learn more about WebAudio first rather than hacking at it), but there is an annoying problem that you notice that it behaves differently on difference browsers/architectures.
