### ISSUE TITLE
Repeat bars are not taken into account

### ISSUE THREAD

**Issue by efreja** [rism-digital/midi-player#24]
And I guess first & second ends, and so on. They are just ignored...
Thanks

**Comment by craigsapp** [comment]
Yes.  But this is not a problem in the midi-player itself, but rather a complication related to exporting MIDI from verovio.  MIDI sequencers require you to prepare the repeated materials in a through-composed MIDI file.

Verovio has an `--expand` option that can be used to produce a score/MIDI file with expanded repeats.  Is there a demo/documentation page about this @lpugin?  (this is related to issue https://github.com/rism-ch/verovio/issues/235).

If you want an unexpanded score but an expanded MIDI performance, this is a future feature for verovio (see the last post in the above issue for notes related to that).

**Comment by lpugin** [comment]
Yes, this is not an issue for the player.
